apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgBiGveK93tnwbkLYdosHDHYCSsI80w1r3tC0Sdgif6LW29P9vqarLdSqJao+RmT9ZROWsNKEN0GM8MEUcEmQ6lPAJFUkb9Aq/xXQxwH2MSytl+fq6it55sK+2OiMB5MNvElU40GIqRSdjpcjH3wwmLVm00txxf7yCAmSrwNW1Im31LVpu7l6GfucDXGx+LKuCCFVvitpsnfvSxkoZmusN/eNwG5XT/rPY/QU/a++WC4mDh8QB07SRaeouBouPsYHZlAKrMkjrejFhZt8WPeuEhvJHiV7Azv3dEdnOXmQpvRmBTOAzsTjEurVoCYTZybRrdsZQfq4CA6nAaLkL9YP41QjgA/OK44PpY5MDinn6tUNP19j0+8Y6BHl/b7GO2qKLhGYH5UfEfEh358JZtJ8rT0EnZOXrIUI7i/B/JuoZV3TAcuU1qWlVb5HT554jjDUx315Htw8+wh2G36A8UCbfscBhM0rNMN/euE/cuM2MrPqkRd7Qa6vg2Q2BudxlgeO/x4rSbzl1iMIz11tLJwZ6FPdwqXRjD4P8apcTspHJn9aS5/IzkN/MnELzxhD8BBbfTxdO2m9ICRyaiRzubSOqawzHQYroOd/XRcOxNIJCFipzLRil3bl6jEqFgUdWExkIVdsd92Qv3iEWHxPsBif/OPEdJ0UjHzSpoMnFA9dwjFrG2qX7GdW6iyAIadLNmlFl6UWNObn1/g3swVWcwwxF/sX1uemnL/6XriwrXl8fkvKDpmn5CKIg==
    ARTIFACTORY_PASSWORD: AgCQK9L4oNhey1NEPOFkuPahsxelJdVBHc94FCozq0PEcCaEY30B86hW7WDG1SHgTLCy5qYI2S9Ut7p/YmjEt+KiCtyigFB58MPoFfIKgpk6UIXtTtZYojVd2QlGs8NEb8Ww5fLtIGCd+55Xr/nxZwgfEDjmGeFdjnz+DbRNbaV9bpCQl9RqSR/MQIo/LeVQLAiNELC70YTAyxXwpE2t0Iov/AM5/O3gvvTPKN05aKriSqK5QKxbubKQ+A4Q2Y1sVSmoyo7GYu+PHtWudkTdH87vYss3rLmplVInl8dD8WQpuXv8QY/Aw09mH+w2Top+Oa1ba9m1FVR27IqRa6Gt01uDDtcOEAWmQl+81Svr9r/DzDOnlYk7Ib6cVRsvb+tROTaE9yfe7w3tt8uSQnVqQX0hK0pk8xSAYEcfs/0jGm5+B+fk6pZ+Yx+BUWr0prhby1ejexlOOqW14b8auzicS/iO+Ojv64Lu/5Gru7CpCFpeZYtk4XmYioK2ZX9ru8XBZdtg7ANlRJErP1gCTzjuDl8udvAhThqCGt4er9h2cDHznlo3Xrcq/jy2x28tcNADzt+oSwGtdwhUdgw2HAbrzBlON3BzaryRmWVTJM9QgpyJYc4C8S2trW02vTBxJpKpJ8PXW5wnw3VfDGQEHJWeQQ8cPmhD+ee7ZXRxVUxiAVVMxnBD/jOuDh6fKzveKM21QFR0KRlxntkXt+CwZP2VvTsNEhrKTA==
    ARTIFACTORY_URL: AgCnq9GMhF37l/1sHpbkCZQAVl4BBxURshOR635QqmjkzDDwM6nmmbTicOunu6hLwT8RmmuGfh/dxy7ZriPfbO58mJr8oURBQgj0tLTcya7M/X0LIm1D4EwkmjCH+K3HwGxfH8ndvja89A0H5yBOuqvfVYI/Y8/OXdlJKRPB6JUWYL34LN/14BJMTMPTA6TSxr3t0/LkGysoIVr7TjCbr1QG90ev9YlKCmm6I6CcLuxE8+EcEwEu4trX0o9uqAnGCNa86KEropYUw3wFnYNFz7v3dXc2AhCOYxmPkDx9g36xCZfS5rBwf9gtQXU8RYR0zMacxQ0OWjuWa1DVCkIWyENvpVSGRgX7im92e8r8CpXd7MPdREM7STkC/DuT/w2n04hJTxQnneRrwENabCAJZYi+cKYF2wwcwZzK7w+1ckbrxyc1VseJlAdg9MFCBjatkufUEuOXD9DoY7+e+xgnrA23GiSMAkQ/3lNVNshNLszdvS78a4H3LAjblQgRhk5QW1KWGFLHb+yBaWrqAyaKqNZuAqWLRLmyeiXoGUmuPTfeK5DdD05U4mjyqYu1COO4fNam67k/XlQV3u5B18XJWkeHcy1iraiYY/quBki9Ije1V2T9Xet+oq2IDpF273X2zB1rlIgaMGHtmUmDtnCa2Fj3HaKK0Y7hIvUF860K9RAe6g+5MTbRe8xYXqG1kxUgUXW2b82xTZVnRGstxnn5yBze3Z4vlC6Ul45JBBasdJDaOIwCrgGB3v79/A==
    ARTIFACTORY_USER: AgCq8imenGKV5nq4+tYPtXW4DRmKfPPAooHPibAG/TPkp97Su5y2wt7e0I1zXJ8XPxIq7JrNOHUzfZIZ4NYfVhTXbHoZ7Jd/dHqkTdxeplvrl8NHilhRpLKbgFVm7Fzy5p3FJ4pcjZFUmEIvj00MiKmAsAV1Q+1LtPpdbHweB8s5c/IrME34poFQolnEaoCGscqD2LwqGDQhwrkmu3urD47+wk0wdaIWGbyAzkNNIhhl2VGkWPHt+2QjxILcaPNMZF+Rx23RbzBkXFibJMMjJFrdw/kSl/ILjG+uhFXBl8160rXrJRjPYTQi8xHL3ol91RT6xOwA5VjN4ltNcxUsLxdoZUfPs7733gUhIB58QpIWt65ooLWQSEbK5/cnSVijmzjoH1dc9TCpUA78qaB+4mT0C2rMQFr8qLVqcXsxs3JDLVVJa3ODyFncg+Z8R56bQdjPdrcMQtNVxDa05YK4GiAfG6SHKNGGDEanO9B4neJSh4lP2HiW+ZS+SmvGJDIcgKMdLK6qSmHWfd5cy9waZjQekTxYyWQ+DzX49KWrqD+pz329wbxXUBrlP2p0sGi/KspsSVhN+enk3NwUDWJRsBKysOcRc8NzUBWqHOs6y4Ehb1R05yNBMDhI51Ei0adwH3ln6/gpfj0bEQQWuvYoiL8NF3VbB/793mryoFnJkiqGLCXlzaOIkZU4VgUICXJzl/rrRSRp/w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-08-23T14:31:22Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-08-23T14:32:44Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

