apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgCnul5eJTyTAl60uZ4YON4Cx7+Zb6zVKY7z64IjT0OTVucKttNu8LO3ilnP9I51Rmza/bWpewyzykWb/R2Qg5u/wlb2nhJtXSpRxT3zkuay3obAGyFkJ6alVFrFQKJ2w9NVyEMUFordXaoO5tgdKu6R0+BlU5TP2rjhnMSXRM15TAqfFBiPz6GD6Q23nUUjbv5CfoO3Y0mcqctL4rPRBYwRctA61PDGju8KzTkcoRzrgvo2l9A+6WFonddBUfOaGMznw3S9/8GBWYb/E8Fg41qbGwhuZjfGaJD7vC1+goJhtrKA0hzYJ/L3JD7LNOlkt5bldGrc02NBT+HUsMDEYNaSiVrUujZ+bWYjqevoMVtvtuI17FD6zhGy93KPxR9/YpEsUvAKVuVhV8mlMQIOAlxbvyo1MsJeWmpIhP2vCctiga1OVbx0P/rYnabKKEhd8mVTh/wXoXfFglwyF2fRlMUblIxqmXDfEswVR4Esn1zSbN2Unwhbswn7SewFYsCRt20ed+WGKWWeQJepL4CGLppQvnn12d9bghg4q8wiOJpVIjoQe5yDz7XcUbJQSe/TXM3zRMp/zK+t24nXchkSKI4/IK/PY83ZssRpbYXvCAD4Bq/Xq4MzicwDaqzxx3EjO8FZ1jDm91V5A5R48OQ+ZX1uR37xcKuLEVp39d1rON+51ZRGIDvt2RVxkBRuhyoSe90wP4He9xF/0Yi2dCs18s+qi60aU6h+iQDBIRgXaEzlsh9G1ZSLe3S2
    username: AgCQuFDbqNC4uOp8EaH8JE5JTQtiRcuFtehAiDWgg1Njj19tiNu7q/peVnhvo5SLwO9/gxzxkKL6w+TjS8IpjrPXCJHe6IAWDv79uzukYD54lAHFeeQo7d7Fxa9AEqbq4n0Xd4gLOe6iLenQ2qdnL7WhziUECy2mst+1pAmUfjgT7qU/6blqsp5ATBW9bQnG+d5tIWEIb8LuPACITy+VVljnlqqo09cHosSFRinuYkwHiSN1IM71qRlaxf2zjiFSLj7ZJwD2XJCXONiIR1iOH7ruKh7rcpf6hPwNc/fuPZ2bw+Csap6m4JQu5o4owB2jy+7oZTdDuXXMwyfKIYy+j4Z5KHtuxkmECSeemHtfrSj6GBG76+N1nqQrroDX7S0KxkpjWhK2vCoYf84LuG7OhZM+/sA+3wfLpdBPuS8jvSeO4WmlXaZoMKeGeAvAymh872OTQ4vVaY6WLB1CNwGmmdOUko/2r75/swxjNJ10oe06mo9FPRUCnnzYLmjAr7xBOqoYYY8yRyA+Kg8fxn6otDCTZOeo89XYNLVdJaTDdhUuPbNUk6YvfEil1i32I3ovQ+HS/4O1cBgVDJhirUYsdYiw37ETg2ZZwh2Tpme8o7n6GWqHMppig9jGge/wr0Q28ubndYIcYctdRFdu+1pkCUzCO1QFCvQ/eXhzMEEDB7qHKDKSKH80+WbWcvQYyQDFv5P3/dHQqQxAHn8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

